"""Adding image column

Revision ID: 20670a4debf5
Revises: 5218ff0ae6ae
Create Date: 2025-06-16 23:56:07.088744

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '20670a4debf5'
down_revision = '5218ff0ae6ae'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image_path', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.drop_column('image_path')

    # ### end Alembic commands ###
